### PR TITLE
Make index redirect warning case-sensitive

### LINKED ISSUE #1076: Warn if `:main` does not point to an existing file
It is easy to give the wrong casing on this config. Since some file systems are case insensitive it would work locally but not when uploaded to hexdocs.pm.

### PR DESCRIPTION
**Pull request by cybrox**
This intends to fix #1076

Tests are passing on both, case-sensitive system (Arch Linux with ext4) and case-insensitive system (OSX with ... uhm, their FS). Also, a warning is now correctly displayed on OSX.

I adjusted the test to cover this case as well, however, it doesn't really prove much. Not sure if this suffices or if we have to think of some way to actually make this behaviour testable on any system. - I couldn't think of an easy way of simulating the case-insensitive behaviour on my work machine / the CI)

### CODE REVIEW

File: lib/ex_doc/formatter/html.ex [hunk 1]
```diff
@@ -375,14 +375,22 @@ defmodule ExDoc.Formatter.HTML do
...
-    unless File.regular?("#{config.output}/#{redirect_to}") do
+    unless module_file_exists("#{config.output}/#{redirect_to}") do
       IO.puts(:stderr, "warning: #{filename} redirects to #{redirect_to}, which does not exist")
     end
 
     content = Templates.redirect_template(config, redirect_to)
     File.write!("#{config.output}/#{filename}", content)
   end
 
+  defp module_file_exists(path) do
```
Comment (ericmj) [inline lib/ex_doc/formatter/html.ex]: Why `module_`? What about `case_sensitive_file_regular?/1`?

File: lib/ex_doc/formatter/html.ex [hunk 2]
```diff
@@ -375,14 +375,22 @@ defmodule ExDoc.Formatter.HTML do
...
+    files = path |> Path.dirname() |> File.ls!()
```
Comment (josevalim) [inline lib/ex_doc/formatter/html.ex]: The directory may not exist, which means the `ls!` operation here can fail. Maybe check for `File.regular?` first and only if it exists, we check for the casing?

Comment (cybrox) [reply lib/ex_doc/formatter/html.ex]: Good point, this was based on the idea that files are generated without subdirectories but I didn't think about the case where a user just puts an invalid output directory.

File: lib/ex_doc/formatter/html.ex [hunk 3]
```diff
@@ -375,14 +375,24 @@ defmodule ExDoc.Formatter.HTML do
...
     end
 
     content = Templates.redirect_template(config, redirect_to)
     File.write!("#{config.output}/#{filename}", content)
   end
 
+  defp case_sensitive_file_regular?(path) do
+    if File.regular?(path) do
+      files = path |> Path.dirname() |> File.ls!()
+      file = path |> Path.basename()
```
Comment (eksperimental) [inline lib/ex_doc/formatter/html.ex]: No need for the pipe operator

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
