### PR TITLE
Fix duplicated API Reference heading

### LINKED ISSUE #1409: Duplicate `API Reference` title in 0.25.4
image

```html
   82 <h1 id="content">
   83 API Reference
   84 
   85 </h1>
   86 
   87 <h1>
   88   API Reference <small class="app-vsn">foobar v0.1.0</small>
   89 </h1>
```

### PR DESCRIPTION
**Pull request by jonatanklosko**
Closes #1409.

### CODE REVIEW

File: lib/ex_doc/formatter/html.ex [hunk 1]
```diff
@@ -292,13 +292,16 @@ defmodule ExDoc.Formatter.HTML do
   end
 
   defp build_api_reference(nodes_map, config) do
-    api_reference = Templates.api_reference_template(config, nodes_map)
+    api_reference = Templates.api_reference_template(nodes_map)
+
+    title_content =
+      ~s{API Reference <small class="app-vsn">#{config.project} v#{config.version}</small>}
```
Comment (jonatanklosko) [inline lib/ex_doc/formatter/html.ex:298]: Do we want to include the version for all extras as well, or just for the APIs?
