### PR TITLE
Tokenize function names on search

### LINKED ISSUE #1381: Search does not work on punctuation marks
Examples:

https://hexdocs.pm/elixir/search.html?q=all%3F
[https://hexdocs.pm/elixir/search.html?q=struct!](https://hexdocs.pm/elixir/search.html?q=struct!)

### PR DESCRIPTION
**Pull request by vinibrsl**
By default, the Lunr language processor splits words by spaces, and trims
special characters. This works for most cases, but when searching for
functions such as `Enum.all?`, nothing was returned.

This commit splits functions by module name, function name, and arity.
By providing this custom processor, the default trimming is skipped in
this scenario.

Closes #1381

### CODE REVIEW

File: assets/js/search-page.js [hunk 1]
```diff
@@ -133,6 +134,26 @@ function snakeCaseSplitter (builder) {
   builder.pipeline.before(lunr.stemmer, snakeCaseFunction)
 }
 
+function elixirFunctionSplitter (builder) {
+  function splitter (token) {
+    const functionTokens = token
+      .toString()
+      .split(/\.|\//)
```
Comment (vinibrsl) [inline assets/js/search-page.js:141]: For instance:

```
> "Enum.any?/2".split(/\.|\//)
[ 'Enum', 'any?', '2' ]
```

Comment (josevalim) [reply assets/js/search-page.js:141]: Should we merge this splitter with the previous splitter? 🤔  And then split everything on `.` and `/`?

Comment (vinibrsl) [reply assets/js/search-page.js]: Thanks for the suggestion. I pushed the changes.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
