### PR TITLE
Run code formatter on typespecs

### LINKED ISSUE #799: Complex types formatting
Currently it's only broken on `|`, and so e.g. on complex structs it looks like this:

zrzut ekranu 2017-11-26 o 18 36 35

(https://hexdocs.pm/ecto/Ecto.Changeset.html#t:t/0)

Ideally, we'd get back something similar to what formatter can do:

```
iex> IO.puts Code.format_string!("t() :: %Ecto.Changeset{action: action, changes: %{optional(atom) => term}, constraints: [constraint], data: Ecto.Schema.t | map | nil, empty_values: term, errors: [{atom, error}], filters: %{optional(atom) => term}, params: %{optional(String.t) => term} | nil, prepare: [(t -> t)], repo: atom | nil, repo_opts: Keyword.t, required: [atom], types: nil | %{optional(atom) => Ecto.Type.t}, valid?: boolean, validations: Keyword.t}")
t() :: %Ecto.Changeset{
  action: action,
  changes: %{optional(atom) => term},
  constraints: [constraint],
  data: Ecto.Schema.t() | map | nil,
  empty_values: term,
  errors: [{atom, error}],
  filters: %{optional(atom) => term},
  params: %{optional(String.t()) => term} | nil,
  prepare: [(t -> t)],
  repo: atom | nil,
  repo_opts: Keyword.t(),
  required: [atom],
  types: nil | %{optional(atom) => Ecto.Type.t()},
  valid?: boolean,
  validations: Keyword.t()
}
```

### PR DESCRIPTION
**Pull request by wojtekmach**
Closes #799

### CODE REVIEW

**Comment by wojtekmach** [comment]
I did some random testing on Ecto & Elixir codebases and looks pretty good, the only minor regression I've seen is so far is:

before:

zrzut ekranu 2017-11-27 o 02 30 15

(https://hexdocs.pm/elixir/master/File.html#t:mode/0)

after:

zrzut ekranu 2017-11-27 o 02 30 20

**Comment by josevalim** [comment]
How can we fix this regression?

**Comment by wojtekmach** [comment]
it looks like existing code that was breaking on `|` gets in the way, it should probably be disabled or adjusted when formatter is present. Looks relatively easy to fix, stay tuned!

File: lib/ex_doc/formatter/html/autolink.ex [hunk 1]
```diff
@@ -142,32 +154,86 @@ defmodule ExDoc.Formatter.HTML.Autolink do
...
+  defp replace_placeholders(string, placeholders) do
+    Regex.replace(~r"_p\d{3}_", string, &Map.fetch!(placeholders, &1))
+  end
+
+  defp format_ast(ast) do
+    string = Macro.to_string(ast)
+
+    if formatter_available?() do
+      string
+      |> Code.format_string!(line_length: @line_length)
```
Comment (wojtekmach) [inline lib/ex_doc/formatter/html/autolink.ex]: for line_length: 70 I noticed it caused churn in a few places, e.g.: https://hexdocs.pm/elixir/master/Access.html#elem/1 vs:

zrzut ekranu 2017-11-30 o 01 24 31

It might be better to stick to default line length on formatter (which then breaks other tests and I didn't want to necessarily add more `if formatter_available?` clauses or adjust tests 😅 )

**Comment by wojtekmach** [comment]
@josevalim fixed 🎉 :

zrzut ekranu 2017-11-30 o 01 25 14

File: test/ex_doc/formatter/html/autolink_test.exs [hunk 2]
```diff
@@ -233,11 +233,41 @@ defmodule ExDoc.Formatter.HTML.AutolinkTest do
     assert Autolink.typespec(quote(do: (foo(1) :: bar | baz when bat: foo)), [], []) ==
            ~s[foo(1) :: bar | baz when bat: foo]
 
-    assert Autolink.typespec(quote(do: (really_long_name_that_will_trigger_multiple_line_breaks(1) :: bar | baz)), [], []) ==
-           ~s[really_long_name_that_will_trigger_multiple_line_breaks(1) ::\n  bar |\n  baz]
+    if formatter_available?() do
```
Comment (wojtekmach) [inline test/ex_doc/formatter/html/autolink_test.exs]: another option to manage these tests is to have:

```elixir
test "add new lines on |" do
  ...
end

@tag :formatter
test "add new lines on | with formatter" do
  ...
end

@tag :no_formatter
test "add new lines on | without formatter" do
  ...
end
```

and then configure proper exclude in test_helper.exs

Comment (josevalim) [reply test/ex_doc/formatter/html/autolink_test.exs]: I like the tag approach the most.

File: lib/ex_doc/formatter/html/autolink.ex [hunk 3]
```diff
@@ -87,37 +87,49 @@ defmodule ExDoc.Formatter.HTML.Autolink do
...
+    if formatter_available?() do
+      typespec_to_string(ast, typespecs, aliases, lib_dirs)
+    else
+      format_typespec(ast, typespecs, aliases, lib_dirs)
+    end
+  end
 
-  def typespec({:when, _, [{:::, _, [left, {:|, _, _} = center]}, right]} = ast, typespecs, aliases, lib_dirs) do
+  defp format_typespec({:when, _, [{:::, _, [left, {:|, _, _} = center]}, right]} = ast, typespecs, aliases, lib_dirs) do
     if short_typespec?(ast) do
```
Comment (josevalim) [inline lib/ex_doc/formatter/html/autolink.ex]: I don't think we need this? We should let the formatter handle it all, no?

File: lib/ex_doc/formatter/html/autolink.ex [hunk 4]
```diff
@@ -142,32 +154,86 @@ defmodule ExDoc.Formatter.HTML.Autolink do
...
+
+    ast
+    |> format_ast()
+    |> replace_placeholders(placeholders)
   end
 
-  defp short_typespec?(ast) do
-    byte_size(Macro.to_string(ast)) <= 70
+  defp put_placeholder(form, string, placeholders) do
+    id = zero_pad(map_size(placeholders), 3)
```
Comment (josevalim) [inline lib/ex_doc/formatter/html/autolink.ex]: I don't think we need to pad, no?

File: lib/ex_doc/formatter/html/autolink.ex (hunk 1 above)
Comment (josevalim) [reply lib/ex_doc/formatter/html/autolink.ex]: Let's stick with 80, yeah?

File: lib/ex_doc/formatter/html/autolink.ex (hunk 3 above)
Comment (wojtekmach) [reply lib/ex_doc/formatter/html/autolink.ex]: Just to clarify, `format_typespec`, `short_typespec`, `format_typespec_with_new_line`, `normalize_left` will all be gone when we depend on 1.6

File: lib/ex_doc/formatter/html/autolink.ex (hunk 4 above)
Comment (wojtekmach) [reply lib/ex_doc/formatter/html/autolink.ex]: yup, not anymore as there's always a trailing `_`

File: lib/ex_doc/formatter/html/autolink.ex (hunk 3 above)
Comment (josevalim) [reply lib/ex_doc/formatter/html/autolink.ex]: Oh, sorry. I got confused. I thought `format_typespec`used the formatter (since it says format in the name) and I thought that `typespec_to_string` used `Macro.to_string` since it has `to_string`. Should we flip the names?

Comment (wojtekmach) [reply lib/ex_doc/formatter/html/autolink.ex]: doh, good call! All fixed now

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
