### PR TITLE
Add metadata to ast and fix HTML escaping

### LINKED ISSUE #1189: Rendering regression in 0.22
Hey,

In version `0.21` it was rendering markdown with HTML blocks as expected for example the following block 

```html
<h1 align="center">
Bla bla
</h1>
<p align="center">
  <img width="150" height="150" src="https://image.svg"/>
</p>
```

In version 0.22 `ex_doc` renders tags as plain text.

Also parser is unable to properly parse text blocks for example if you put
```html
<h1 align="center">Title</h1>
```
It will render

```html
Title</h1>
```

Elixir version: 1.10.3
earmark: 1.4.5
makeup: 1.0.3
makeup_elixir: 0.14.1

Thanks.

### PR DESCRIPTION
**Pull request by wojtekmach**
Closes #1189

### CODE REVIEW

File: test/ex_doc/markdown/earmark_test.exs [hunk 1]
```diff
@@ -28,7 +37,7 @@ defmodule ExDoc.Markdown.EarmarkTest do
 
     test "bug #1222" do
```
Comment (josevalim) [inline test/ex_doc/markdown/earmark_test.exs:38]:
```suggestion
    test "handles warnings" do
```

**Review by josevalim — COMMENTED** [review]
Looks great! Can we also verify the fix with a unit test? I want to depend less and less on integration tests.
