### PR TITLE
Fix missing assets in the header section

### LINKED ISSUE #619: Fix bugs in EPUB format
- [x] Mimetype file entry is missing or is not the first file in the archive.
- [x] Delete `OEBPS/assets/logo.png` at the end of the process, is still remaining.
- [ ] Fix missing assets in the header section: `<link type="text/css" rel="stylesheet" href="" />` or `<script src=""></script>`.
- [ ] Declare all the assets (images, JS, CSS) in the OPF manifest.
- [ ] Support the `:group` option from extras

### PR DESCRIPTION
**Pull request by milmazz**
* Reduce the number of args required in some functions.
* Fix references to assets in the OPF manifest.
* Compress JS files when creating ZIP

Fixes #619

### CODE REVIEW

File: lib/ex_doc/formatter/epub.ex [hunk 1]
```diff
@@ -34,20 +30,25 @@ defmodule ExDoc.Formatter.EPUB do
...
+    File.rm_rf!(config.output)
     epub_file
   end
 
   defp normalize_config(config) do
+    output =
+      config.output
+      |> Path.expand()
+      |> Path.join("#{config.project}-v#{config.version}")
+    config = Map.put(config, :output, output)
```
Comment (josevalim) [inline lib/ex_doc/formatter/epub.ex]: `%{config | output: output}` would be semantically better (as the key `:output` is guaranteed to exist and is being updated).

**Comment by josevalim** [comment]
@milmazz just one tiny comment then go ahead and :shipit: :D

File: lib/ex_doc/formatter/epub.ex (hunk 1 above)
Comment (milmazz) [inline lib/ex_doc/formatter/epub.ex]: Sweet!
