### PR TITLE
Use Hexdocs format in :otp anchors

### LINKED ISSUE #1907: links for otp apps' (gen_tcp/ssl) types use old format
:wave:

Docs for a type like
```elixir
@type socket :: :gen_tcp.socket() | :ssl.sslsocket()
```
generate incorrect links to the new Erlang docs.

Generated:
- https://www.erlang.org/doc/apps/kernel/gen_tcp.html#type-socket
- https://www.erlang.org/doc/apps/ssl/ssl.html#type-sslsocket

Should be:
- https://www.erlang.org/doc/apps/kernel/gen_tcp.html#t:socket/0
- https://www.erlang.org/doc/apps/ssl/ssl.html#t:sslsocket/0

Example: https://hexdocs.pm/mua/Mua.html#t:socket/0

Mua's ExDoc is at v0.33.0: https://github.com/ruslandoga/mua/blob/73122aef37ce098e125c5e921e100bcdf61d19ef/mix.lock#L6

### PR DESCRIPTION
**Pull request by ruslandoga**
closes #1907

### CODE REVIEW

File: test/ex_doc/formatter/html/erlang_test.exs [hunk 1]
```diff
@@ -36,10 +36,10 @@ defmodule ExDoc.Formatter.HTML.ErlangTest do
              ~s|-spec</span> foo(<a href=\"#t:t/0\">t</a>()) -&gt; <a href=\"#t:t/0\">t</a>().|
 
     assert html =~
-             ~s|-type</span> t() :: <a href=\"https://www.erlang.org/doc/man/erlang.html#type-atom\">atom</a>().|
+             ~s|-type</span> t() :: <a href=\"https://www.erlang.org/doc/man/erlang.html#t:atom/0\">atom</a>().|
```
Comment (ruslandoga) [inline test/ex_doc/formatter/html/erlang_test.exs:39]: ✅ https://www.erlang.org/doc/apps/erts/erlang.html#t:atom/0

File: test/ex_doc/formatter/html/erlang_test.exs [hunk 2]
```diff
@@ -36,10 +36,10 @@ defmodule ExDoc.Formatter.HTML.ErlangTest do
...
 
     assert html =~
-             ~s|-type</span> t2() :: #rec{k1 :: <a href=\"https://www.erlang.org/doc/man/uri_string.html#type-uri_string\">uri_string:uri_string</a>(), k2 :: <a href=\"https://www.erlang.org/doc/man/uri_string.html#type-uri_string\">uri_string:uri_string</a>() \| undefined}.|
+             ~s|-type</span> t2() :: #rec{k1 :: <a href=\"https://www.erlang.org/doc/man/uri_string.html#t:uri_string/0\">uri_string:uri_string</a>(), k2 :: <a href=\"https://www.erlang.org/doc/man/uri_string.html#t:uri_string/0\">uri_string:uri_string</a>() \| undefined}.|
```
Comment (ruslandoga) [inline test/ex_doc/formatter/html/erlang_test.exs:42]: ✅ https://www.erlang.org/doc/man/uri_string.html#t:uri_string/0 redirects to https://www.erlang.org/doc/apps/stdlib/uri_string.html#t:uri_string/0

File: test/ex_doc/language/elixir_test.exs [hunk 3]
```diff
@@ -99,7 +99,7 @@ defmodule ExDoc.Language.ElixirTest do
 
     test "erlang stdlib function" do
       assert autolink_doc("`:lists.all/2`") ==
-               ~s|<a href="https://www.erlang.org/doc/man/lists.html#all-2"><code class="inline">:lists.all/2</code></a>|
+               ~s|<a href="https://www.erlang.org/doc/man/lists.html#all/2"><code class="inline">:lists.all/2</code></a>|
```
Comment (ruslandoga) [inline test/ex_doc/language/elixir_test.exs:102]: ✅ https://www.erlang.org/doc/apps/stdlib/lists.html#all/2

File: test/ex_doc/language/elixir_test.exs [hunk 4]
```diff
@@ -150,7 +150,7 @@ defmodule ExDoc.Language.ElixirTest do
 
     test "erlang callback" do
       assert autolink_doc("`c::gen_server.handle_call/3`") ==
-               ~s|<a href="https://www.erlang.org/doc/man/gen_server.html#Module:handle_call-3"><code class="inline">:gen_server.handle_call/3</code></a>|
+               ~s|<a href="https://www.erlang.org/doc/man/gen_server.html#c:handle_call/3"><code class="inline">:gen_server.handle_call/3</code></a>|
```
Comment (ruslandoga) [inline test/ex_doc/language/elixir_test.exs:153]: ✅ https://www.erlang.org/doc/apps/stdlib/gen_server.html#c:handle_call/3

File: test/ex_doc/language/elixir_test.exs [hunk 5]
```diff
@@ -171,7 +171,7 @@ defmodule ExDoc.Language.ElixirTest do
 
     test "erlang type" do
       assert autolink_doc("`t::array.array/0`") ==
-               ~s|<a href="https://www.erlang.org/doc/man/array.html#type-array"><code class="inline">:array.array/0</code></a>|
+               ~s|<a href="https://www.erlang.org/doc/man/array.html#t:array/0"><code class="inline">:array.array/0</code></a>|
```
Comment (ruslandoga) [inline test/ex_doc/language/elixir_test.exs:174]: ✅ https://www.erlang.org/doc/man/array.html#t:array/0 redirects to https://www.erlang.org/doc/apps/stdlib/array.html#t:array/0

File: test/ex_doc/language/elixir_test.exs [hunk 6]
```diff
@@ -207,7 +207,7 @@ defmodule ExDoc.Language.ElixirTest do
                ~s|<a href="https://www.erlang.org/doc/man/lists.html">custom text</a>|
 
       assert autolink_doc("[custom text](`:lists.all/2`)") ==
-               ~s|<a href="https://www.erlang.org/doc/man/lists.html#all-2">custom text</a>|
+               ~s|<a href="https://www.erlang.org/doc/man/lists.html#all/2">custom text</a>|
```
Comment (ruslandoga) [inline test/ex_doc/language/elixir_test.exs:210]: ✅ https://www.erlang.org/doc/apps/stdlib/lists.html#all/2

File: test/ex_doc/language/elixir_test.exs [hunk 7]
```diff
@@ -450,7 +450,7 @@ defmodule ExDoc.Language.ElixirTest do
 
     test "Erlang stdlib types" do
       assert autolink_spec(quote(do: t() :: :sets.set())) ==
-               ~s[t() :: <a href="https://www.erlang.org/doc/man/sets.html#type-set">:sets.set</a>()]
+               ~s[t() :: <a href="https://www.erlang.org/doc/man/sets.html#t:set/0">:sets.set</a>()]
```
Comment (ruslandoga) [inline test/ex_doc/language/elixir_test.exs:453]: ✅ https://www.erlang.org/doc/man/sets.html#t:set/0 redirects to https://www.erlang.org/doc/apps/stdlib/sets.html#t:set/0

File: test/ex_doc/formatter/html/erlang_test.exs (hunk 2 above)
Comment (ruslandoga) [reply test/ex_doc/formatter/html/erlang_test.exs:42]: Should we update these links as well or is it OK to rely on www.erlang.org to always perform this redirect?

Comment (josevalim) [reply test/ex_doc/formatter/html/erlang_test.exs:42]: I would say let's go ahead and link to the new page! Especially as I assume it will be less code? But we can do it in a next PR. :)

**Comment by ruslandoga** [comment]
Tests in test/ex_doc/language/erlang_test.exs fail. These tests are excluded when I run `mix test`, I guess because asdf installs Erlang without docs.

File: test/ex_doc/language/erlang_test.exs [hunk 8]
```diff
@@ -789,12 +789,12 @@ defmodule ExDoc.Language.ErlangTest do
...
     test "OTP type", c do
       assert autolink_spec(~S"-spec foo() -> sets:set().", c) ==
-               ~s|foo() -> <a href="https://www.erlang.org/doc/man/sets.html#type-set">sets:set</a>().|
+               ~s|foo() -> <a href="https://www.erlang.org/doc/man/sets.html#t:set/0">sets:set</a>().|
     end
 
     test "OTP private type", c do
       assert autolink_spec(~S"-spec foo() -> array:array_indx().", c) ==
-               ~s|foo() -> <a href="https://www.erlang.org/doc/man/array.html#type-array_indx">array:array_indx</a>().|
+               ~s|foo() -> array:array_indx().|
```
Comment (ruslandoga) [inline test/ex_doc/language/erlang_test.exs:797]: This one "lost" its link to https://www.erlang.org/doc/apps/stdlib/array.html#t:array_indx/0

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by josevalim** [comment]
Beautiful! Can you also please send a PR that updates from doc/man to doc/apps/APP? Thank you!

**Comment by ruslandoga** [comment]
👋 @josevalim 

The next PR is ready for review: https://github.com/elixir-lang/ex_doc/pull/1909
